/*********************************************************************
    a game developed by harisu fanyui to help improve on the memory
    capacity of children and adult
    developed on 25/08/2015 this program is typical and was coded in windows so some functions might not work correctly in linux eg system("cls")
**********************************************************************/

#include<stdio.h>
#include<stdlib.h>
#include<time.h>
#include<string.h>
#include<ctype.h>
#include<process.h>
#include<windows.h>
#include<conio.h>
#include<ctype.h>
int flag=0;//to tell if a stage is completed successfully
int stagedata;//to store the data at a particular stage
void load();//to load the game
void stage1();//FUCNTION FOR STAGE
void stage2();
void stage3();
void pause(int x);//TO PAUSE FOR A PARTICULAR NUMBER OF TIME
char name[15];//to store the users  name
int num1,num2,num3;//random number generated by the machine
int resp1,resp2,resp3;//the value given by the user
   // struct screenposition{
   //     int x;
   //     int y;
   // };
   void appenddata();//to append new data and new stage the user has reached
    void gettoposition(int x,int y);//screen coordinates
int fileconstructor();//to check if the user exist in a file or he is new to the game
int main(){
int stage_from_function;//to store the value to be returned from fileconstructor fucnt
srand(time(NULL));//generate random time
int ch;

int response;
printf("****************************************************************************\n");
printf("*\t\t\t\tSMARTSOFT FROM SMARTLAB\t\t\t*\n");
printf("\n|Welcome to this timing game it is going to help you develope your brain\n");
printf("\n|you have to store the numbers generated by the machine and give it back when\n");
printf("\n|you are asked to by the machine\n");
printf("|\nin order to move to the next stage you have to complete the first stage first\n");
printf("\n****************************************************************************\n\n");
printf("what is your name please...?\n");
scanf("%s",name);
printf("\n|do you want to begin the game (y/n)\n\n\n");
getch();
load();
stage_from_function= fileconstructor();
if (stage_from_function==1)
        goto stage1;
else if (stage_from_function==2)
            goto stage2;
else if (stage_from_function==3)
    goto stage3;
mainmenu:


stage1://lebel for stage 1
    stage1();
    if (flag!=0){
            printf("enter 1 to go to stage 2 or zero to play this stage again\n");
            scanf("%d",&response);
            if (response==0)
                goto stage1;

        else {
stage2: //lebel for stage 2
            stage2();
            if (flag!=0){//checking to make sure that the user succceded stage 2
                    printf("enter 1 to go to stage 1 or \n2 to play this stage again or 3 to go to stage 3\n");
                        scanf("%d",&response);
                        if (response==1)
                            goto stage1;
                        else if (response==2)
                            goto stage2;
                        else if (response==3) {
stage3://lebel for stage 3
                                stage3();
                        }
                        else
                                printf("invalid response\n try to follow instructions next time\n");
            }//end of checking for success in stage 2
            else printf("sorry you didnot succeed stage 2 and cannot go ahead\n");
        }
    }
    else printf("sorry you did not succeed in stage 1\n");
    printf("\n\n\n");
appenddata();
    printf("THANKS FOR USING THIS GAME HOPE YOU ENJOYED IT \n subscrib on my facebook page at HARISU FANYUI\n or send me a mail at fanyuiharisu@gmail.com for more products\nTill then enjoy yours...goodluck\n");
printf("enter a digit to go to main menu or any other to exit\n");
if (isdigit(getch()))
    goto mainmenu;
else exit(0);
return 0;
}
//stage 1 function definition
void stage1(){
    stagedata=1;
num1=rand()%100;
num2=rand()%100;
num3=rand()%100;

printf("%d\t%d\t%d\n",num1,num2,num3);
pause(5);

system("cls");
printf("enter the numbers you saw\n");
scanf("%d %d %d",&resp1,&resp2,&resp3);
if((resp1==num1)&&(resp2==num2)&&(resp3==num3)){
    printf("you got it correct good job mr %s\n",name);
        flag=1;
    }
else {
        printf("sorry mr %s the correct numbers are\n",name);
            flag=0;
}
    printf("\t%d\t%d\t%d\n",num1,num2,num3);
    printf("you gave %d\t%d\t%d\n",resp1,resp2,resp3);


}

//function to pause for the specified time as parameter
void pause(int x){
    unsigned int start,stop;
        start=time(0);
    do{
            stop=time(0);
    }
    while(stop-start!=x);
}
//function for stage 2 slightly difficult
void stage2(){
    stagedata=2;
num1=rand()%1000;
num2=rand()%1000;
num3=rand()%1000;
printf("welcome to stage 2\n");
printf("enter any character to continue\n");
getch();
printf("%d\t%d\t%d\n",num1,num2,num3);

pause(6);
system("cls");
printf("enter the numbers you saw\n");
scanf("%d %d %d",&resp1,&resp2,&resp3);
    if((resp1==num1)&&(resp2==num2)&&(resp3==num3)){
        printf("good job M %s you are now ready for the next lesson\n",name);
            flag=2;
    }
    else {
            printf("sorry the correct numbers are\n");
            flag=0;
    }
    printf("\t%d\t%d\t%d\n",num1,num2,num3);
    printf("you gave %d\t%d\t%d\n",resp1,resp2,resp3);

}
//function for stage3 the most difficult part of the game
void stage3(){
    stagedata=3;
num1=rand()%10000;
num2=rand()%10000;
num3=rand()%10000;

printf("%d\t%d\t%d\n",num1,num2,num3);
pause(7);
system("cls");
printf("enter the numbers you saw\n");
scanf("%d %d %d",&resp1,&resp2,&resp3);
if((resp1==num1)&&(resp2==num2)&&(resp3==num3)){
        printf("Good job m %s your brain is super fast \n",name);
        printf("you can now go in for memory competition \n");

        flag=3;
}
else{
        printf("sorry the correct numbers are\n");
        flag=0;
}
    printf("\t%d\t%d\t%d\n",num1,num2,num3);
    printf("you gave %d\t%d\t%d\n",resp1,resp2,resp3);

}
//provides the screen coordinate position to start loading
void gettoposition(int x,int y){
COORD position1;
position1.X=x;
position1.Y=y;
    SetConsoleCursorPosition(GetStdHandle(STD_OUTPUT_HANDLE),position1);
    //SetConsoleCursorPosition(GetstdHandle(STD_OUTPUT_HANDLE),position1);
}
//the load fucntion to load the game on the screen
void load(){

    int i,j;
    system("cls");
    gettoposition(36,14);//starting  screen coordinate
    printf("loading...");
    gettoposition(30,15);//
    for(i=0;i<10;i++){
        for(j=0;j<500000000;j++);//to delay the printing of the various characters
            printf("%c",177);//print the ascii character of letter 177

    }
    //getch();
    printf("\n");
    system("cls");
}
//tells the state at which a particular user left the game and if he want to continue from there or start a new one
int fileconstructor(){
    char name1[15];
    int stageflage=0;

    FILE *frecord;//pointer to the record file
    int state;
    frecord=fopen("game_record.txt","r");
    if (frecord==NULL)
        printf("cannot open record file\n");
    else
    {
        while(!feof(frecord)){
            fscanf(frecord,"%s %d",name1,&stageflage);
            if(strcmp(name,name1)==0)
            {
                printf(" To continue you last saved game press 1 or\n");
                printf(" 2 start a new game\n");
                scanf("%d",&state);
                if (state==1)
                    return stageflage;
                //else exit(0);
            }
        }
        //fprintf(frecord,"%s %d\n",name,1);
    }
fclose(frecord);
}
//functions to create and swap new game_records text files
void appenddata(){
    char name1[15];
    int stageflage;
FILE *frecord;
FILE *temp;//pointer to temporal file which will be made permanent at the end
temp=fopen("newfile.txt","w");
if (temp==NULL)
    printf("cannot create newfile\n");
 frecord=fopen("game_record.txt","r");
    if (frecord==NULL)
        printf("cannot open record file\n");
    else{ while(!feof(frecord)){
                    fscanf(frecord,"%s %d",name1,&stageflage);///reading from old gamerecord file
                if (strcmp(name,name1)==0)
                    continue;
                else{
                       fprintf(temp,"%s %d\n",name1,stageflage);//writing to newfile.txt file
                }
            }
    fprintf(temp,"%s %d\n",name,stagedata);
    }
    fclose(frecord);
    fclose(temp);
    //the next two lines is there to swap the names of the newfile and game_record
    remove("game_record.txt");
    rename("newfile.txt","game_record.txt");
}
